server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

jwt:
  key:
    secret: "28d93268-a80b-4594-918b-5926a79a49ed"
  access-token-expiration-minutes: 1440
  refresh-token-expiration-minutes: 1440

file:
  img: /Users/hipo/Desktop/Img/

iam:
  access-key: local
  secret-key: local
  region: local

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

mod: local